parameters:
    # None

services:
    exercise1.service:
        class: AppBundle\Services\Exercise1Service
        arguments:
            - '@request_stack'

    exercise2.service:
        class: AppBundle\Services\Exercise2Service

    exercise3.service:
        class: AppBundle\Services\Exercise3Service

    exercise4.service:
        class: AppBundle\Services\Exercise4Service

